# Generated by Django 5.2.8 on 2025-11-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('company', models.CharField(blank=True, max_length=500)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('apply_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
