# Generated by Django 5.2.8 on 2025-11-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
