# Generated by Django 5.2.8 on 2025-11-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0002_rename_content_jobposting_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
    ]
