# Generated by Django 5.2.8 on 2025-11-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0003_badjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='badjob',
            name='company',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='badjob',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='badjob',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='badjob',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='badjob',
            name='scraped_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='badjob',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='badjob',
            name='title',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
