# Generated by Django 5.2.8 on 2026-02-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0004_badjob_company_badjob_description_badjob_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
