# Generated by Django 5.2.8 on 2026-02-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0005_badcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text="Case-insensitive substring to block (e.g. 'London', 'EMEA')", max_length=500, unique=True)),
            ],
        ),
    ]
