# Generated by Django 5.2.8 on 2026-02-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0006_badlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='badjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='badjob',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
